oq = input("Digite algo: ")

print(f"O tipo primitivo desse valor é {type(oq)}")
print(f"Só tem espaços? {oq.isspace()}")
print(f"É um número? {oq.isnumeric()}")
print(f"É alfabético? {oq.isalpha()}")
print(f"É alfanúmerico? {oq.isalnum()}")
print(f"Está em maiúsculo? {oq.isupper()}")
print(f"Está em minúsculo? {oq.islower()}")
print(f"A primeira letra é maiúscula? {oq.istitle()}")
print(f"É um símbolo? {oq.isascii()}")
print(f"É uma string de digitos? {oq.isdigit()}")
print(f"Pode ser impresso? {oq.isprintable()}")
print(f"Pode ser um código python {oq.isidentifier()}")
print(f"É um número inteiro? {oq.isdecimal()}")